<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Malgorzata M. Jakubowska" />

<meta name="date" content="2016-09-15" />

<title>Practical Machine Learning</title>

<script src="PML_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PML_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="PML_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PML_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PML_files/bootstrap-3.3.5/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="PML_files/highlight/default.css"
      type="text/css" />
<script src="PML_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="PML_files/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Practical Machine Learning</h1>
<h4 class="author"><em>Malgorzata M. Jakubowska</em></h4>
<h4 class="date"><em>15 September 2016</em></h4>

</div>


<p>The aim of the following report is to provide the reader with the overview of the process of building a machine learning algorithm based on the Weight Lifting Exercise Dataset (Velloso, Bulling, Gellersen, Ugulino &amp; Fuks, 2013). As opposed to predicting the type of activity performed, the algorithm is thought to model the “goodness” of the performance, which is a new strain of the human activity recognition studies. The report will cover the buliding procedure step by step. #### The Weight Lifting Exercise Dataset includes data collected from six participants performing the Unilateral Dumbbell Biceps Curl in five distinct ways. Those ways correspond to the “classe” variable, which is supposed to be predicted by other variables from the dataset. Class A is assigned to a perfect performance and Classes B-E reflect different errors. Apart from the “classe” variable both sets (training and test) contain 159 variables. There are 19622 observations in the training set and 20 in the test set.</p>
<div id="data-reading" class="section level2">
<h2>Data reading</h2>
<p>The first step was to read the data into R.</p>
<pre class="r"><code>training&lt;- read.csv(&quot;pml-training.csv&quot;)
testing&lt;- read.csv(&quot;pml-testing.csv&quot;)</code></pre>
</div>
<div id="data-pre-processing" class="section level2">
<h2>Data pre-processing</h2>
<p>Due to lack of factor variables other than “classe” no dummy variables were needed. However, zero and near zero-variance predictors as well as variables with NA values need to be identified:</p>
<pre class="r"><code>#reading necessary packages
library(caret)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre class="r"><code>#identifying near zero-variance predictors
near0&lt;-nzv(training)
training3&lt;- training[, -near0]
#removing variables with NA values
training4&lt;-Filter(function(x)!any(is.na(x)), training3)
#removing first six variables (user name, timestamps, window)
training5&lt;- training4[, c(7:59)]</code></pre>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<p>The resulting training dataset consists of 53 variables instead of the initial 160. The next step is to further pre-process the data. Having in mind that the training set includes rather large amount of variables, principal component analysis can be applied to possibly reduce the number of variables, so the model training and tuning will be easier to perform. However, since k-fold cross validation will be used, preProcess function will not be calculated separately, but passed as an argument in the train function later, so the PCA is applied to every fold.</p>
<p>An important point must be made here. Due to the possibility of overloading R with excessive amount of data, the following code was used to enable usage of parallel processing.</p>
<pre class="r"><code>library(parallel)
library(doParallel)</code></pre>
<pre><code>## Loading required package: foreach</code></pre>
<pre><code>## Loading required package: iterators</code></pre>
<pre class="r"><code>cluster&lt;-makeCluster(detectCores()-1)
registerDoParallel(cluster)</code></pre>
<p>Running this chunk of code should shorten the time needed to perform the next steps of modeling.</p>
<p>Next, trainControl function is used to generate parameters to later be passed to the train function. The resampling method is k-fold cross-validation with k parameter set to 10.</p>
<pre class="r"><code>control &lt;- trainControl(method = &quot;cv&quot;,
                 number = 10,
                 allowParallel = TRUE)</code></pre>
<p>Now, the initial model training can be performed with the following code. First, seed is set to ensure reproducibility. The model will be trained using random forest approach, following the article by Velloso et al. (2013) in which this procedure was also used. Additionally, as was mentioned before, preProcess function is a part of chunk above, in order to ensure that the principal component analysis is applied to every fold.</p>
<pre class="r"><code>set.seed(1000)
fit &lt;- train(classe~., method=&quot;rf&quot;,data=training5, preProcess=c(&quot;pca&quot;), trControl = control)</code></pre>
<pre><code>## Loading required package: randomForest</code></pre>
<pre><code>## randomForest 4.6-12</code></pre>
<pre><code>## Type rfNews() to see new features/changes/bug fixes.</code></pre>
<pre><code>## 
## Attaching package: &#39;randomForest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     margin</code></pre>
<pre class="r"><code>fit</code></pre>
<pre><code>## Random Forest 
## 
## 19622 samples
##    52 predictor
##     5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## Pre-processing: principal component signal extraction (52), centered
##  (52), scaled (52) 
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 17660, 17659, 17660, 17660, 17661, 17660, ... 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy   Kappa    
##    2    0.9819584  0.9771757
##   27    0.9725819  0.9653189
##   52    0.9722252  0.9648670
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was mtry = 2.</code></pre>
<pre class="r"><code>fit$finalModel</code></pre>
<pre><code>## 
## Call:
##  randomForest(x = x, y = y, mtry = param$mtry) 
##                Type of random forest: classification
##                      Number of trees: 500
## No. of variables tried at each split: 2
## 
##         OOB estimate of  error rate: 1.67%
## Confusion matrix:
##      A    B    C    D    E class.error
## A 5554    7   13    3    3 0.004659498
## B   51 3714   27    0    5 0.021859363
## C    4   34 3358   23    3 0.018702513
## D    4    2  105 3100    5 0.036069652
## E    0    7   20   12 3568 0.010812309</code></pre>
<p>As can be seen in the output, all predictors were centered, scaled and used in the principal component analysis. The resampling method was 10-fold cross-validation. The final mtry parameter chosen was 2, which means that two variables were tried at each split in the classification tree. Accuracy of the final model is 0.982, Kappa is equal to 0.977 and out-of-sample error is 1.67%. It can be concluded that the model performance is satisfactory.</p>
<p>Below variable importance plot (based on variables resulting from the PCA) and the confusion matrix can be seen .</p>
<pre class="r"><code>imp&lt;-varImp(fit)
plot(imp)</code></pre>
<p><img src="PML_files/figure-html/unnamed-chunk-6-1.png" alt="" /><!-- --></p>
<pre class="r"><code>confusionMatrix(fit)</code></pre>
<pre><code>## Cross-Validated (10 fold) Confusion Matrix 
## 
## (entries are percentual average cell counts across resamples)
##  
##           Reference
## Prediction    A    B    C    D    E
##          A 28.3  0.3  0.0  0.0  0.0
##          B  0.0 18.9  0.2  0.0  0.1
##          C  0.1  0.1 17.1  0.6  0.1
##          D  0.0  0.0  0.2 15.8  0.1
##          E  0.0  0.0  0.0  0.0 18.1
##                            
##  Accuracy (average) : 0.982</code></pre>
<p>The final step would be to predict the “classe” variable on the test set by inputting the following code:</p>
<pre class="r"><code>prediction&lt;-predict(fit, testing)
prediction</code></pre>
<pre><code>##  [1] B A A A A E D B A A B C B A E E A B B B
## Levels: A B C D E</code></pre>
<p>All in all, it can be said that random forest model performance on the Weight Lifting Exercise Dataset is accurate and satisfactory.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
